// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/:resourceId": {
    params: {
      "resourceId": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/admin" | "/admin/:resourceId";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/admin.jsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "./routes/admin.$resourceId.jsx": {
    id: "routes/admin.$resourceId";
    page: "/admin/:resourceId";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "routes/home": typeof import("./src/./routes/home.jsx");
  "routes/admin": typeof import("./src/./routes/admin.jsx");
  "routes/admin.$resourceId": typeof import("./src/./routes/admin.$resourceId.jsx");
};